// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class BitbucketDatacenterIntegration extends pulumi.CustomResource {
    /**
     * Get an existing BitbucketDatacenterIntegration resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: BitbucketDatacenterIntegrationState, opts?: pulumi.CustomResourceOptions): BitbucketDatacenterIntegration {
        return new BitbucketDatacenterIntegration(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'spacelift-terraform-provider:index/bitbucketDatacenterIntegration:BitbucketDatacenterIntegration';

    /**
     * Returns true if the given object is an instance of BitbucketDatacenterIntegration.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is BitbucketDatacenterIntegration {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === BitbucketDatacenterIntegration.__pulumiType;
    }

    /**
     * User access token from Bitbucket
     */
    declare public readonly accessToken: pulumi.Output<string>;
    /**
     * The API host where requests will be sent
     */
    declare public readonly apiHost: pulumi.Output<string>;
    /**
     * Bitbucket Datacenter integration description
     */
    declare public readonly description: pulumi.Output<string>;
    /**
     * Bitbucket Datacenter integration is default.
     */
    declare public readonly isDefault: pulumi.Output<boolean>;
    /**
     * Bitbucket Datacenter integration labels
     */
    declare public readonly labels: pulumi.Output<string[]>;
    /**
     * Bitbucket Datacenter integration name
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Bitbucket Datacenter integration space id. Defaults to `root`.
     */
    declare public readonly spaceId: pulumi.Output<string>;
    /**
     * Indicates whether the integration should use git checkout. If false source code will be downloaded using the VCS API.
     * Defaults to false.
     */
    declare public readonly useGitCheckout: pulumi.Output<boolean>;
    /**
     * User Facing Host which will be used for all user-facing URLs displayed in the Spacelift UI
     */
    declare public readonly userFacingHost: pulumi.Output<string>;
    /**
     * Username which will be used to authenticate requests for cloning repositories
     */
    declare public readonly username: pulumi.Output<string>;
    /**
     * VCS checks configured for Bitbucket Datacenter repositories. Possible values: INDIVIDUAL, AGGREGATED, ALL. Defaults to
     * INDIVIDUAL.
     */
    declare public readonly vcsChecks: pulumi.Output<string | undefined>;
    /**
     * Secret for webhooks originating from Bitbucket repositories
     */
    declare public /*out*/ readonly webhookSecret: pulumi.Output<string>;
    /**
     * URL for webhooks originating from Bitbucket repositories
     */
    declare public /*out*/ readonly webhookUrl: pulumi.Output<string>;

    /**
     * Create a BitbucketDatacenterIntegration resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: BitbucketDatacenterIntegrationArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: BitbucketDatacenterIntegrationArgs | BitbucketDatacenterIntegrationState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as BitbucketDatacenterIntegrationState | undefined;
            resourceInputs["accessToken"] = state?.accessToken;
            resourceInputs["apiHost"] = state?.apiHost;
            resourceInputs["description"] = state?.description;
            resourceInputs["isDefault"] = state?.isDefault;
            resourceInputs["labels"] = state?.labels;
            resourceInputs["name"] = state?.name;
            resourceInputs["spaceId"] = state?.spaceId;
            resourceInputs["useGitCheckout"] = state?.useGitCheckout;
            resourceInputs["userFacingHost"] = state?.userFacingHost;
            resourceInputs["username"] = state?.username;
            resourceInputs["vcsChecks"] = state?.vcsChecks;
            resourceInputs["webhookSecret"] = state?.webhookSecret;
            resourceInputs["webhookUrl"] = state?.webhookUrl;
        } else {
            const args = argsOrState as BitbucketDatacenterIntegrationArgs | undefined;
            if (args?.accessToken === undefined && !opts.urn) {
                throw new Error("Missing required property 'accessToken'");
            }
            if (args?.apiHost === undefined && !opts.urn) {
                throw new Error("Missing required property 'apiHost'");
            }
            if (args?.isDefault === undefined && !opts.urn) {
                throw new Error("Missing required property 'isDefault'");
            }
            if (args?.userFacingHost === undefined && !opts.urn) {
                throw new Error("Missing required property 'userFacingHost'");
            }
            if (args?.username === undefined && !opts.urn) {
                throw new Error("Missing required property 'username'");
            }
            resourceInputs["accessToken"] = args?.accessToken ? pulumi.secret(args.accessToken) : undefined;
            resourceInputs["apiHost"] = args?.apiHost;
            resourceInputs["description"] = args?.description;
            resourceInputs["isDefault"] = args?.isDefault;
            resourceInputs["labels"] = args?.labels;
            resourceInputs["name"] = args?.name;
            resourceInputs["spaceId"] = args?.spaceId;
            resourceInputs["useGitCheckout"] = args?.useGitCheckout;
            resourceInputs["userFacingHost"] = args?.userFacingHost;
            resourceInputs["username"] = args?.username;
            resourceInputs["vcsChecks"] = args?.vcsChecks;
            resourceInputs["webhookSecret"] = undefined /*out*/;
            resourceInputs["webhookUrl"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["accessToken", "webhookSecret"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(BitbucketDatacenterIntegration.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering BitbucketDatacenterIntegration resources.
 */
export interface BitbucketDatacenterIntegrationState {
    /**
     * User access token from Bitbucket
     */
    accessToken?: pulumi.Input<string>;
    /**
     * The API host where requests will be sent
     */
    apiHost?: pulumi.Input<string>;
    /**
     * Bitbucket Datacenter integration description
     */
    description?: pulumi.Input<string>;
    /**
     * Bitbucket Datacenter integration is default.
     */
    isDefault?: pulumi.Input<boolean>;
    /**
     * Bitbucket Datacenter integration labels
     */
    labels?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Bitbucket Datacenter integration name
     */
    name?: pulumi.Input<string>;
    /**
     * Bitbucket Datacenter integration space id. Defaults to `root`.
     */
    spaceId?: pulumi.Input<string>;
    /**
     * Indicates whether the integration should use git checkout. If false source code will be downloaded using the VCS API.
     * Defaults to false.
     */
    useGitCheckout?: pulumi.Input<boolean>;
    /**
     * User Facing Host which will be used for all user-facing URLs displayed in the Spacelift UI
     */
    userFacingHost?: pulumi.Input<string>;
    /**
     * Username which will be used to authenticate requests for cloning repositories
     */
    username?: pulumi.Input<string>;
    /**
     * VCS checks configured for Bitbucket Datacenter repositories. Possible values: INDIVIDUAL, AGGREGATED, ALL. Defaults to
     * INDIVIDUAL.
     */
    vcsChecks?: pulumi.Input<string>;
    /**
     * Secret for webhooks originating from Bitbucket repositories
     */
    webhookSecret?: pulumi.Input<string>;
    /**
     * URL for webhooks originating from Bitbucket repositories
     */
    webhookUrl?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a BitbucketDatacenterIntegration resource.
 */
export interface BitbucketDatacenterIntegrationArgs {
    /**
     * User access token from Bitbucket
     */
    accessToken: pulumi.Input<string>;
    /**
     * The API host where requests will be sent
     */
    apiHost: pulumi.Input<string>;
    /**
     * Bitbucket Datacenter integration description
     */
    description?: pulumi.Input<string>;
    /**
     * Bitbucket Datacenter integration is default.
     */
    isDefault: pulumi.Input<boolean>;
    /**
     * Bitbucket Datacenter integration labels
     */
    labels?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Bitbucket Datacenter integration name
     */
    name?: pulumi.Input<string>;
    /**
     * Bitbucket Datacenter integration space id. Defaults to `root`.
     */
    spaceId?: pulumi.Input<string>;
    /**
     * Indicates whether the integration should use git checkout. If false source code will be downloaded using the VCS API.
     * Defaults to false.
     */
    useGitCheckout?: pulumi.Input<boolean>;
    /**
     * User Facing Host which will be used for all user-facing URLs displayed in the Spacelift UI
     */
    userFacingHost: pulumi.Input<string>;
    /**
     * Username which will be used to authenticate requests for cloning repositories
     */
    username: pulumi.Input<string>;
    /**
     * VCS checks configured for Bitbucket Datacenter repositories. Possible values: INDIVIDUAL, AGGREGATED, ALL. Defaults to
     * INDIVIDUAL.
     */
    vcsChecks?: pulumi.Input<string>;
}
