// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getAzureDevopsIntegration(args?: GetAzureDevopsIntegrationArgs, opts?: pulumi.InvokeOptions): Promise<GetAzureDevopsIntegrationResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("spacelift:index/getAzureDevopsIntegration:getAzureDevopsIntegration", {
        "id": args.id,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getAzureDevopsIntegration.
 */
export interface GetAzureDevopsIntegrationArgs {
    id?: string;
}

/**
 * A collection of values returned by getAzureDevopsIntegration.
 */
export interface GetAzureDevopsIntegrationResult {
    readonly description: string;
    readonly id?: string;
    readonly isDefault: boolean;
    readonly labels: string[];
    readonly name: string;
    readonly organizationUrl: string;
    readonly spaceId: string;
    readonly vcsChecks: string;
    readonly webhookPassword: string;
    readonly webhookUrl: string;
}
export function getAzureDevopsIntegrationOutput(args?: GetAzureDevopsIntegrationOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetAzureDevopsIntegrationResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("spacelift:index/getAzureDevopsIntegration:getAzureDevopsIntegration", {
        "id": args.id,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getAzureDevopsIntegration.
 */
export interface GetAzureDevopsIntegrationOutputArgs {
    id?: pulumi.Input<string>;
}
