// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getAzureIntegrationAttachment(args: GetAzureIntegrationAttachmentArgs, opts?: pulumi.InvokeOptions): Promise<GetAzureIntegrationAttachmentResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("spacelift-terraform-provider:index/getAzureIntegrationAttachment:getAzureIntegrationAttachment", {
        "id": args.id,
        "integrationId": args.integrationId,
        "moduleId": args.moduleId,
        "stackId": args.stackId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getAzureIntegrationAttachment.
 */
export interface GetAzureIntegrationAttachmentArgs {
    id?: string;
    integrationId: string;
    moduleId?: string;
    stackId?: string;
}

/**
 * A collection of values returned by getAzureIntegrationAttachment.
 */
export interface GetAzureIntegrationAttachmentResult {
    readonly attachmentId: string;
    readonly id: string;
    readonly integrationId: string;
    readonly moduleId?: string;
    readonly read: boolean;
    readonly stackId?: string;
    readonly subscriptionId: string;
    readonly write: boolean;
}
export function getAzureIntegrationAttachmentOutput(args: GetAzureIntegrationAttachmentOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetAzureIntegrationAttachmentResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("spacelift-terraform-provider:index/getAzureIntegrationAttachment:getAzureIntegrationAttachment", {
        "id": args.id,
        "integrationId": args.integrationId,
        "moduleId": args.moduleId,
        "stackId": args.stackId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getAzureIntegrationAttachment.
 */
export interface GetAzureIntegrationAttachmentOutputArgs {
    id?: pulumi.Input<string>;
    integrationId: pulumi.Input<string>;
    moduleId?: pulumi.Input<string>;
    stackId?: pulumi.Input<string>;
}
