// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getAzureIntegrations(args?: GetAzureIntegrationsArgs, opts?: pulumi.InvokeOptions): Promise<GetAzureIntegrationsResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("spacelift-terraform-provider:index/getAzureIntegrations:getAzureIntegrations", {
        "id": args.id,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getAzureIntegrations.
 */
export interface GetAzureIntegrationsArgs {
    id?: string;
}

/**
 * A collection of values returned by getAzureIntegrations.
 */
export interface GetAzureIntegrationsResult {
    readonly id: string;
    readonly integrations: outputs.GetAzureIntegrationsIntegration[];
}
export function getAzureIntegrationsOutput(args?: GetAzureIntegrationsOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetAzureIntegrationsResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("spacelift-terraform-provider:index/getAzureIntegrations:getAzureIntegrations", {
        "id": args.id,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getAzureIntegrations.
 */
export interface GetAzureIntegrationsOutputArgs {
    id?: pulumi.Input<string>;
}
