// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getAwsIntegrationAttachmentExternalId(args: GetAwsIntegrationAttachmentExternalIdArgs, opts?: pulumi.InvokeOptions): Promise<GetAwsIntegrationAttachmentExternalIdResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("spacelift-terraform-provider:index/getAwsIntegrationAttachmentExternalId:getAwsIntegrationAttachmentExternalId", {
        "id": args.id,
        "integrationId": args.integrationId,
        "moduleId": args.moduleId,
        "read": args.read,
        "stackId": args.stackId,
        "write": args.write,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getAwsIntegrationAttachmentExternalId.
 */
export interface GetAwsIntegrationAttachmentExternalIdArgs {
    id?: string;
    integrationId: string;
    moduleId?: string;
    read?: boolean;
    stackId?: string;
    write?: boolean;
}

/**
 * A collection of values returned by getAwsIntegrationAttachmentExternalId.
 */
export interface GetAwsIntegrationAttachmentExternalIdResult {
    readonly assumeRolePolicyStatement: string;
    readonly externalId: string;
    readonly id: string;
    readonly integrationId: string;
    readonly moduleId?: string;
    readonly read?: boolean;
    readonly stackId?: string;
    readonly write?: boolean;
}
export function getAwsIntegrationAttachmentExternalIdOutput(args: GetAwsIntegrationAttachmentExternalIdOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetAwsIntegrationAttachmentExternalIdResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("spacelift-terraform-provider:index/getAwsIntegrationAttachmentExternalId:getAwsIntegrationAttachmentExternalId", {
        "id": args.id,
        "integrationId": args.integrationId,
        "moduleId": args.moduleId,
        "read": args.read,
        "stackId": args.stackId,
        "write": args.write,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getAwsIntegrationAttachmentExternalId.
 */
export interface GetAwsIntegrationAttachmentExternalIdOutputArgs {
    id?: pulumi.Input<string>;
    integrationId: pulumi.Input<string>;
    moduleId?: pulumi.Input<string>;
    read?: pulumi.Input<boolean>;
    stackId?: pulumi.Input<string>;
    write?: pulumi.Input<boolean>;
}
