// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getAwsIntegrationAttachment(args: GetAwsIntegrationAttachmentArgs, opts?: pulumi.InvokeOptions): Promise<GetAwsIntegrationAttachmentResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("spacelift-terraform-provider:index/getAwsIntegrationAttachment:getAwsIntegrationAttachment", {
        "id": args.id,
        "integrationId": args.integrationId,
        "moduleId": args.moduleId,
        "stackId": args.stackId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getAwsIntegrationAttachment.
 */
export interface GetAwsIntegrationAttachmentArgs {
    id?: string;
    integrationId: string;
    moduleId?: string;
    stackId?: string;
}

/**
 * A collection of values returned by getAwsIntegrationAttachment.
 */
export interface GetAwsIntegrationAttachmentResult {
    readonly attachmentId: string;
    readonly id: string;
    readonly integrationId: string;
    readonly moduleId?: string;
    readonly read: boolean;
    readonly stackId?: string;
    readonly write: boolean;
}
export function getAwsIntegrationAttachmentOutput(args: GetAwsIntegrationAttachmentOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetAwsIntegrationAttachmentResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("spacelift-terraform-provider:index/getAwsIntegrationAttachment:getAwsIntegrationAttachment", {
        "id": args.id,
        "integrationId": args.integrationId,
        "moduleId": args.moduleId,
        "stackId": args.stackId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getAwsIntegrationAttachment.
 */
export interface GetAwsIntegrationAttachmentOutputArgs {
    id?: pulumi.Input<string>;
    integrationId: pulumi.Input<string>;
    moduleId?: pulumi.Input<string>;
    stackId?: pulumi.Input<string>;
}
