// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getAwsIntegrations(args?: GetAwsIntegrationsArgs, opts?: pulumi.InvokeOptions): Promise<GetAwsIntegrationsResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("spacelift:index/getAwsIntegrations:getAwsIntegrations", {
        "id": args.id,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getAwsIntegrations.
 */
export interface GetAwsIntegrationsArgs {
    id?: string;
}

/**
 * A collection of values returned by getAwsIntegrations.
 */
export interface GetAwsIntegrationsResult {
    readonly id: string;
    readonly integrations: outputs.GetAwsIntegrationsIntegration[];
}
export function getAwsIntegrationsOutput(args?: GetAwsIntegrationsOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetAwsIntegrationsResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("spacelift:index/getAwsIntegrations:getAwsIntegrations", {
        "id": args.id,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getAwsIntegrations.
 */
export interface GetAwsIntegrationsOutputArgs {
    id?: pulumi.Input<string>;
}
