// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getBitbucketCloudIntegration(args?: GetBitbucketCloudIntegrationArgs, opts?: pulumi.InvokeOptions): Promise<GetBitbucketCloudIntegrationResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("spacelift:index/getBitbucketCloudIntegration:getBitbucketCloudIntegration", {
        "id": args.id,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getBitbucketCloudIntegration.
 */
export interface GetBitbucketCloudIntegrationArgs {
    id?: string;
}

/**
 * A collection of values returned by getBitbucketCloudIntegration.
 */
export interface GetBitbucketCloudIntegrationResult {
    readonly description: string;
    readonly id?: string;
    readonly isDefault: boolean;
    readonly labels: string[];
    readonly name: string;
    readonly spaceId: string;
    readonly username: string;
    readonly vcsChecks: string;
    readonly webhookUrl: string;
}
export function getBitbucketCloudIntegrationOutput(args?: GetBitbucketCloudIntegrationOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetBitbucketCloudIntegrationResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("spacelift:index/getBitbucketCloudIntegration:getBitbucketCloudIntegration", {
        "id": args.id,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getBitbucketCloudIntegration.
 */
export interface GetBitbucketCloudIntegrationOutputArgs {
    id?: pulumi.Input<string>;
}
