// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getCurrentSpace(args?: GetCurrentSpaceArgs, opts?: pulumi.InvokeOptions): Promise<GetCurrentSpaceResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("spacelift:index/getCurrentSpace:getCurrentSpace", {
        "id": args.id,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getCurrentSpace.
 */
export interface GetCurrentSpaceArgs {
    id?: string;
}

/**
 * A collection of values returned by getCurrentSpace.
 */
export interface GetCurrentSpaceResult {
    readonly description: string;
    readonly id: string;
    readonly inheritEntities: boolean;
    readonly labels: string[];
    readonly name: string;
    readonly parentSpaceId: string;
}
export function getCurrentSpaceOutput(args?: GetCurrentSpaceOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetCurrentSpaceResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("spacelift:index/getCurrentSpace:getCurrentSpace", {
        "id": args.id,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getCurrentSpace.
 */
export interface GetCurrentSpaceOutputArgs {
    id?: pulumi.Input<string>;
}
