// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getCurrentStack(args?: GetCurrentStackArgs, opts?: pulumi.InvokeOptions): Promise<GetCurrentStackResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("spacelift:index/getCurrentStack:getCurrentStack", {
        "id": args.id,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getCurrentStack.
 */
export interface GetCurrentStackArgs {
    id?: string;
}

/**
 * A collection of values returned by getCurrentStack.
 */
export interface GetCurrentStackResult {
    readonly id: string;
}
export function getCurrentStackOutput(args?: GetCurrentStackOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetCurrentStackResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("spacelift:index/getCurrentStack:getCurrentStack", {
        "id": args.id,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getCurrentStack.
 */
export interface GetCurrentStackOutputArgs {
    id?: pulumi.Input<string>;
}
