// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getEnvironmentVariable(args: GetEnvironmentVariableArgs, opts?: pulumi.InvokeOptions): Promise<GetEnvironmentVariableResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("spacelift-terraform-provider:index/getEnvironmentVariable:getEnvironmentVariable", {
        "contextId": args.contextId,
        "id": args.id,
        "moduleId": args.moduleId,
        "name": args.name,
        "stackId": args.stackId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getEnvironmentVariable.
 */
export interface GetEnvironmentVariableArgs {
    contextId?: string;
    id?: string;
    moduleId?: string;
    name: string;
    stackId?: string;
}

/**
 * A collection of values returned by getEnvironmentVariable.
 */
export interface GetEnvironmentVariableResult {
    readonly checksum: string;
    readonly contextId?: string;
    readonly description: string;
    readonly id: string;
    readonly moduleId?: string;
    readonly name: string;
    readonly stackId?: string;
    readonly value: string;
    readonly writeOnly: boolean;
}
export function getEnvironmentVariableOutput(args: GetEnvironmentVariableOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetEnvironmentVariableResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("spacelift-terraform-provider:index/getEnvironmentVariable:getEnvironmentVariable", {
        "contextId": args.contextId,
        "id": args.id,
        "moduleId": args.moduleId,
        "name": args.name,
        "stackId": args.stackId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getEnvironmentVariable.
 */
export interface GetEnvironmentVariableOutputArgs {
    contextId?: pulumi.Input<string>;
    id?: pulumi.Input<string>;
    moduleId?: pulumi.Input<string>;
    name: pulumi.Input<string>;
    stackId?: pulumi.Input<string>;
}
