// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getGitlabIntegration(args?: GetGitlabIntegrationArgs, opts?: pulumi.InvokeOptions): Promise<GetGitlabIntegrationResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("spacelift:index/getGitlabIntegration:getGitlabIntegration", {
        "id": args.id,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getGitlabIntegration.
 */
export interface GetGitlabIntegrationArgs {
    id?: string;
}

/**
 * A collection of values returned by getGitlabIntegration.
 */
export interface GetGitlabIntegrationResult {
    readonly apiHost: string;
    readonly description: string;
    readonly id?: string;
    readonly isDefault: boolean;
    readonly labels: string[];
    readonly name: string;
    readonly spaceId: string;
    readonly useGitCheckout: boolean;
    readonly vcsChecks: string;
    readonly webhookSecret: string;
    readonly webhookUrl: string;
}
export function getGitlabIntegrationOutput(args?: GetGitlabIntegrationOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetGitlabIntegrationResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("spacelift:index/getGitlabIntegration:getGitlabIntegration", {
        "id": args.id,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getGitlabIntegration.
 */
export interface GetGitlabIntegrationOutputArgs {
    id?: pulumi.Input<string>;
}
