// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getGithubEnterpriseIntegration(args?: GetGithubEnterpriseIntegrationArgs, opts?: pulumi.InvokeOptions): Promise<GetGithubEnterpriseIntegrationResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("spacelift:index/getGithubEnterpriseIntegration:getGithubEnterpriseIntegration", {
        "id": args.id,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getGithubEnterpriseIntegration.
 */
export interface GetGithubEnterpriseIntegrationArgs {
    id?: string;
}

/**
 * A collection of values returned by getGithubEnterpriseIntegration.
 */
export interface GetGithubEnterpriseIntegrationResult {
    readonly apiHost: string;
    readonly appId: string;
    readonly description: string;
    readonly id?: string;
    readonly isDefault: boolean;
    readonly labels: string[];
    readonly name: string;
    readonly spaceId: string;
    readonly vcsChecks: string;
    readonly webhookSecret: string;
    readonly webhookUrl: string;
}
export function getGithubEnterpriseIntegrationOutput(args?: GetGithubEnterpriseIntegrationOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetGithubEnterpriseIntegrationResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("spacelift:index/getGithubEnterpriseIntegration:getGithubEnterpriseIntegration", {
        "id": args.id,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getGithubEnterpriseIntegration.
 */
export interface GetGithubEnterpriseIntegrationOutputArgs {
    id?: pulumi.Input<string>;
}
