// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getGcpServiceAccount(args?: GetGcpServiceAccountArgs, opts?: pulumi.InvokeOptions): Promise<GetGcpServiceAccountResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("spacelift:index/getGcpServiceAccount:getGcpServiceAccount", {
        "id": args.id,
        "moduleId": args.moduleId,
        "stackId": args.stackId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getGcpServiceAccount.
 */
export interface GetGcpServiceAccountArgs {
    id?: string;
    moduleId?: string;
    stackId?: string;
}

/**
 * A collection of values returned by getGcpServiceAccount.
 */
export interface GetGcpServiceAccountResult {
    readonly id: string;
    readonly moduleId?: string;
    readonly serviceAccountEmail: string;
    readonly stackId?: string;
    readonly tokenScopes: string[];
}
export function getGcpServiceAccountOutput(args?: GetGcpServiceAccountOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetGcpServiceAccountResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("spacelift:index/getGcpServiceAccount:getGcpServiceAccount", {
        "id": args.id,
        "moduleId": args.moduleId,
        "stackId": args.stackId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getGcpServiceAccount.
 */
export interface GetGcpServiceAccountOutputArgs {
    id?: pulumi.Input<string>;
    moduleId?: pulumi.Input<string>;
    stackId?: pulumi.Input<string>;
}
