// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getIps(args?: GetIpsArgs, opts?: pulumi.InvokeOptions): Promise<GetIpsResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("spacelift:index/getIps:getIps", {
        "id": args.id,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getIps.
 */
export interface GetIpsArgs {
    id?: string;
}

/**
 * A collection of values returned by getIps.
 */
export interface GetIpsResult {
    readonly cidrs: string[];
    readonly id: string;
    readonly ips: string[];
}
export function getIpsOutput(args?: GetIpsOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetIpsResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("spacelift:index/getIps:getIps", {
        "id": args.id,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getIps.
 */
export interface GetIpsOutputArgs {
    id?: pulumi.Input<string>;
}
