// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getMountedFile(args: GetMountedFileArgs, opts?: pulumi.InvokeOptions): Promise<GetMountedFileResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("spacelift-terraform-provider:index/getMountedFile:getMountedFile", {
        "contextId": args.contextId,
        "id": args.id,
        "moduleId": args.moduleId,
        "relativePath": args.relativePath,
        "stackId": args.stackId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getMountedFile.
 */
export interface GetMountedFileArgs {
    contextId?: string;
    id?: string;
    moduleId?: string;
    relativePath: string;
    stackId?: string;
}

/**
 * A collection of values returned by getMountedFile.
 */
export interface GetMountedFileResult {
    readonly checksum: string;
    readonly content: string;
    readonly contextId?: string;
    readonly id: string;
    readonly moduleId?: string;
    readonly relativePath: string;
    readonly stackId?: string;
    readonly writeOnly: boolean;
}
export function getMountedFileOutput(args: GetMountedFileOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetMountedFileResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("spacelift-terraform-provider:index/getMountedFile:getMountedFile", {
        "contextId": args.contextId,
        "id": args.id,
        "moduleId": args.moduleId,
        "relativePath": args.relativePath,
        "stackId": args.stackId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getMountedFile.
 */
export interface GetMountedFileOutputArgs {
    contextId?: pulumi.Input<string>;
    id?: pulumi.Input<string>;
    moduleId?: pulumi.Input<string>;
    relativePath: pulumi.Input<string>;
    stackId?: pulumi.Input<string>;
}
