// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getNamedWebhook(args: GetNamedWebhookArgs, opts?: pulumi.InvokeOptions): Promise<GetNamedWebhookResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("spacelift-terraform-provider:index/getNamedWebhook:getNamedWebhook", {
        "id": args.id,
        "webhookId": args.webhookId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getNamedWebhook.
 */
export interface GetNamedWebhookArgs {
    id?: string;
    webhookId: string;
}

/**
 * A collection of values returned by getNamedWebhook.
 */
export interface GetNamedWebhookResult {
    readonly enabled: boolean;
    readonly endpoint: string;
    readonly id: string;
    readonly labels: string[];
    readonly name: string;
    readonly secretHeaderKeys: string[];
    readonly spaceId: string;
    readonly webhookId: string;
}
export function getNamedWebhookOutput(args: GetNamedWebhookOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetNamedWebhookResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("spacelift-terraform-provider:index/getNamedWebhook:getNamedWebhook", {
        "id": args.id,
        "webhookId": args.webhookId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getNamedWebhook.
 */
export interface GetNamedWebhookOutputArgs {
    id?: pulumi.Input<string>;
    webhookId: pulumi.Input<string>;
}
