// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getRoleActions(args?: GetRoleActionsArgs, opts?: pulumi.InvokeOptions): Promise<GetRoleActionsResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("spacelift-terraform-provider:index/getRoleActions:getRoleActions", {
        "id": args.id,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRoleActions.
 */
export interface GetRoleActionsArgs {
    id?: string;
}

/**
 * A collection of values returned by getRoleActions.
 */
export interface GetRoleActionsResult {
    readonly actions: string[];
    readonly id: string;
}
export function getRoleActionsOutput(args?: GetRoleActionsOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetRoleActionsResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("spacelift-terraform-provider:index/getRoleActions:getRoleActions", {
        "id": args.id,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRoleActions.
 */
export interface GetRoleActionsOutputArgs {
    id?: pulumi.Input<string>;
}
