// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getSavedFilter(args: GetSavedFilterArgs, opts?: pulumi.InvokeOptions): Promise<GetSavedFilterResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("spacelift-terraform-provider:index/getSavedFilter:getSavedFilter", {
        "filterId": args.filterId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSavedFilter.
 */
export interface GetSavedFilterArgs {
    filterId: string;
}

/**
 * A collection of values returned by getSavedFilter.
 */
export interface GetSavedFilterResult {
    readonly createdBy: string;
    readonly data: string;
    readonly filterId: string;
    readonly id: string;
    readonly isPublic: boolean;
    readonly name: string;
    readonly type: string;
}
export function getSavedFilterOutput(args: GetSavedFilterOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSavedFilterResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("spacelift-terraform-provider:index/getSavedFilter:getSavedFilter", {
        "filterId": args.filterId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSavedFilter.
 */
export interface GetSavedFilterOutputArgs {
    filterId: pulumi.Input<string>;
}
