// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getStackAwsRole(args?: GetStackAwsRoleArgs, opts?: pulumi.InvokeOptions): Promise<GetStackAwsRoleResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("spacelift:index/getStackAwsRole:getStackAwsRole", {
        "id": args.id,
        "moduleId": args.moduleId,
        "stackId": args.stackId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getStackAwsRole.
 */
export interface GetStackAwsRoleArgs {
    id?: string;
    moduleId?: string;
    stackId?: string;
}

/**
 * A collection of values returned by getStackAwsRole.
 */
export interface GetStackAwsRoleResult {
    readonly durationSeconds: number;
    readonly externalId: string;
    readonly generateCredentialsInWorker: boolean;
    readonly id: string;
    readonly moduleId?: string;
    readonly region: string;
    readonly roleArn: string;
    readonly stackId?: string;
}
export function getStackAwsRoleOutput(args?: GetStackAwsRoleOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetStackAwsRoleResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("spacelift:index/getStackAwsRole:getStackAwsRole", {
        "id": args.id,
        "moduleId": args.moduleId,
        "stackId": args.stackId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getStackAwsRole.
 */
export interface GetStackAwsRoleOutputArgs {
    id?: pulumi.Input<string>;
    moduleId?: pulumi.Input<string>;
    stackId?: pulumi.Input<string>;
}
