// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSavedFilters(args?: GetSavedFiltersArgs, opts?: pulumi.InvokeOptions): Promise<GetSavedFiltersResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("spacelift:index/getSavedFilters:getSavedFilters", {
        "filterName": args.filterName,
        "filterType": args.filterType,
        "id": args.id,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSavedFilters.
 */
export interface GetSavedFiltersArgs {
    filterName?: string;
    filterType?: string;
    id?: string;
}

/**
 * A collection of values returned by getSavedFilters.
 */
export interface GetSavedFiltersResult {
    readonly filterName?: string;
    readonly filterType?: string;
    readonly filters: outputs.GetSavedFiltersFilter[];
    readonly id: string;
}
export function getSavedFiltersOutput(args?: GetSavedFiltersOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSavedFiltersResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("spacelift:index/getSavedFilters:getSavedFilters", {
        "filterName": args.filterName,
        "filterType": args.filterType,
        "id": args.id,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSavedFilters.
 */
export interface GetSavedFiltersOutputArgs {
    filterName?: pulumi.Input<string>;
    filterType?: pulumi.Input<string>;
    id?: pulumi.Input<string>;
}
