// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getScheduledDeleteStack(args: GetScheduledDeleteStackArgs, opts?: pulumi.InvokeOptions): Promise<GetScheduledDeleteStackResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("spacelift-terraform-provider:index/getScheduledDeleteStack:getScheduledDeleteStack", {
        "id": args.id,
        "scheduledDeleteStackId": args.scheduledDeleteStackId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getScheduledDeleteStack.
 */
export interface GetScheduledDeleteStackArgs {
    id?: string;
    scheduledDeleteStackId: string;
}

/**
 * A collection of values returned by getScheduledDeleteStack.
 */
export interface GetScheduledDeleteStackResult {
    readonly at: number;
    readonly deleteResources: boolean;
    readonly id: string;
    readonly scheduleId: string;
    readonly scheduledDeleteStackId: string;
    readonly stackId: string;
}
export function getScheduledDeleteStackOutput(args: GetScheduledDeleteStackOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetScheduledDeleteStackResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("spacelift-terraform-provider:index/getScheduledDeleteStack:getScheduledDeleteStack", {
        "id": args.id,
        "scheduledDeleteStackId": args.scheduledDeleteStackId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getScheduledDeleteStack.
 */
export interface GetScheduledDeleteStackOutputArgs {
    id?: pulumi.Input<string>;
    scheduledDeleteStackId: pulumi.Input<string>;
}
