// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getScheduledTask(args: GetScheduledTaskArgs, opts?: pulumi.InvokeOptions): Promise<GetScheduledTaskResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("spacelift:index/getScheduledTask:getScheduledTask", {
        "id": args.id,
        "scheduledTaskId": args.scheduledTaskId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getScheduledTask.
 */
export interface GetScheduledTaskArgs {
    id?: string;
    scheduledTaskId: string;
}

/**
 * A collection of values returned by getScheduledTask.
 */
export interface GetScheduledTaskResult {
    readonly at: number;
    readonly command: string;
    readonly everies: string[];
    readonly id: string;
    readonly scheduleId: string;
    readonly scheduledTaskId: string;
    readonly stackId: string;
    readonly timezone: string;
}
export function getScheduledTaskOutput(args: GetScheduledTaskOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetScheduledTaskResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("spacelift:index/getScheduledTask:getScheduledTask", {
        "id": args.id,
        "scheduledTaskId": args.scheduledTaskId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getScheduledTask.
 */
export interface GetScheduledTaskOutputArgs {
    id?: pulumi.Input<string>;
    scheduledTaskId: pulumi.Input<string>;
}
