// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getSpace(args: GetSpaceArgs, opts?: pulumi.InvokeOptions): Promise<GetSpaceResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("spacelift-terraform-provider:index/getSpace:getSpace", {
        "id": args.id,
        "spaceId": args.spaceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSpace.
 */
export interface GetSpaceArgs {
    id?: string;
    spaceId: string;
}

/**
 * A collection of values returned by getSpace.
 */
export interface GetSpaceResult {
    readonly description: string;
    readonly id: string;
    readonly inheritEntities: boolean;
    readonly labels: string[];
    readonly name: string;
    readonly parentSpaceId: string;
    readonly spaceId: string;
}
export function getSpaceOutput(args: GetSpaceOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSpaceResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("spacelift-terraform-provider:index/getSpace:getSpace", {
        "id": args.id,
        "spaceId": args.spaceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSpace.
 */
export interface GetSpaceOutputArgs {
    id?: pulumi.Input<string>;
    spaceId: pulumi.Input<string>;
}
