// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getScheduledRun(args: GetScheduledRunArgs, opts?: pulumi.InvokeOptions): Promise<GetScheduledRunResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("spacelift-terraform-provider:index/getScheduledRun:getScheduledRun", {
        "at": args.at,
        "everies": args.everies,
        "id": args.id,
        "name": args.name,
        "runtimeConfigs": args.runtimeConfigs,
        "scheduledRunId": args.scheduledRunId,
        "timezone": args.timezone,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getScheduledRun.
 */
export interface GetScheduledRunArgs {
    at?: number;
    everies?: string[];
    id?: string;
    name?: string;
    runtimeConfigs?: inputs.GetScheduledRunRuntimeConfig[];
    scheduledRunId: string;
    timezone?: string;
}

/**
 * A collection of values returned by getScheduledRun.
 */
export interface GetScheduledRunResult {
    readonly at: number;
    readonly everies: string[];
    readonly id: string;
    readonly name: string;
    readonly nextSchedule: number;
    readonly runtimeConfigs?: outputs.GetScheduledRunRuntimeConfig[];
    readonly scheduleId: string;
    readonly scheduledRunId: string;
    readonly stackId: string;
    readonly timezone: string;
}
export function getScheduledRunOutput(args: GetScheduledRunOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetScheduledRunResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("spacelift-terraform-provider:index/getScheduledRun:getScheduledRun", {
        "at": args.at,
        "everies": args.everies,
        "id": args.id,
        "name": args.name,
        "runtimeConfigs": args.runtimeConfigs,
        "scheduledRunId": args.scheduledRunId,
        "timezone": args.timezone,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getScheduledRun.
 */
export interface GetScheduledRunOutputArgs {
    at?: pulumi.Input<number>;
    everies?: pulumi.Input<pulumi.Input<string>[]>;
    id?: pulumi.Input<string>;
    name?: pulumi.Input<string>;
    runtimeConfigs?: pulumi.Input<pulumi.Input<inputs.GetScheduledRunRuntimeConfigArgs>[]>;
    scheduledRunId: pulumi.Input<string>;
    timezone?: pulumi.Input<string>;
}
