// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getSpaceByPath(args: GetSpaceByPathArgs, opts?: pulumi.InvokeOptions): Promise<GetSpaceByPathResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("spacelift-terraform-provider:index/getSpaceByPath:getSpaceByPath", {
        "id": args.id,
        "spacePath": args.spacePath,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSpaceByPath.
 */
export interface GetSpaceByPathArgs {
    id?: string;
    spacePath: string;
}

/**
 * A collection of values returned by getSpaceByPath.
 */
export interface GetSpaceByPathResult {
    readonly description: string;
    readonly id: string;
    readonly inheritEntities: boolean;
    readonly labels: string[];
    readonly name: string;
    readonly parentSpaceId: string;
    readonly spacePath: string;
}
export function getSpaceByPathOutput(args: GetSpaceByPathOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSpaceByPathResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("spacelift-terraform-provider:index/getSpaceByPath:getSpaceByPath", {
        "id": args.id,
        "spacePath": args.spacePath,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSpaceByPath.
 */
export interface GetSpaceByPathOutputArgs {
    id?: pulumi.Input<string>;
    spacePath: pulumi.Input<string>;
}
