// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getVcsAgentPool(args: GetVcsAgentPoolArgs, opts?: pulumi.InvokeOptions): Promise<GetVcsAgentPoolResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("spacelift:index/getVcsAgentPool:getVcsAgentPool", {
        "id": args.id,
        "vcsAgentPoolId": args.vcsAgentPoolId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getVcsAgentPool.
 */
export interface GetVcsAgentPoolArgs {
    id?: string;
    vcsAgentPoolId: string;
}

/**
 * A collection of values returned by getVcsAgentPool.
 */
export interface GetVcsAgentPoolResult {
    readonly description: string;
    readonly id: string;
    readonly name: string;
    readonly vcsAgentPoolId: string;
}
export function getVcsAgentPoolOutput(args: GetVcsAgentPoolOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetVcsAgentPoolResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("spacelift:index/getVcsAgentPool:getVcsAgentPool", {
        "id": args.id,
        "vcsAgentPoolId": args.vcsAgentPoolId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getVcsAgentPool.
 */
export interface GetVcsAgentPoolOutputArgs {
    id?: pulumi.Input<string>;
    vcsAgentPoolId: pulumi.Input<string>;
}
