// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getVcsAgentPools(args?: GetVcsAgentPoolsArgs, opts?: pulumi.InvokeOptions): Promise<GetVcsAgentPoolsResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("spacelift:index/getVcsAgentPools:getVcsAgentPools", {
        "id": args.id,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getVcsAgentPools.
 */
export interface GetVcsAgentPoolsArgs {
    id?: string;
}

/**
 * A collection of values returned by getVcsAgentPools.
 */
export interface GetVcsAgentPoolsResult {
    readonly id: string;
    readonly vcsAgentPools: outputs.GetVcsAgentPoolsVcsAgentPool[];
}
export function getVcsAgentPoolsOutput(args?: GetVcsAgentPoolsOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetVcsAgentPoolsResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("spacelift:index/getVcsAgentPools:getVcsAgentPools", {
        "id": args.id,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getVcsAgentPools.
 */
export interface GetVcsAgentPoolsOutputArgs {
    id?: pulumi.Input<string>;
}
