// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getWebhook(args: GetWebhookArgs, opts?: pulumi.InvokeOptions): Promise<GetWebhookResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("spacelift-terraform-provider:index/getWebhook:getWebhook", {
        "id": args.id,
        "moduleId": args.moduleId,
        "stackId": args.stackId,
        "webhookId": args.webhookId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getWebhook.
 */
export interface GetWebhookArgs {
    id?: string;
    moduleId?: string;
    stackId?: string;
    webhookId: string;
}

/**
 * A collection of values returned by getWebhook.
 */
export interface GetWebhookResult {
    readonly enabled: boolean;
    readonly endpoint: string;
    readonly id: string;
    readonly moduleId?: string;
    readonly stackId?: string;
    readonly webhookId: string;
}
export function getWebhookOutput(args: GetWebhookOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetWebhookResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("spacelift-terraform-provider:index/getWebhook:getWebhook", {
        "id": args.id,
        "moduleId": args.moduleId,
        "stackId": args.stackId,
        "webhookId": args.webhookId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getWebhook.
 */
export interface GetWebhookOutputArgs {
    id?: pulumi.Input<string>;
    moduleId?: pulumi.Input<string>;
    stackId?: pulumi.Input<string>;
    webhookId: pulumi.Input<string>;
}
