// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getWorkerPools(args?: GetWorkerPoolsArgs, opts?: pulumi.InvokeOptions): Promise<GetWorkerPoolsResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("spacelift:index/getWorkerPools:getWorkerPools", {
        "id": args.id,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getWorkerPools.
 */
export interface GetWorkerPoolsArgs {
    id?: string;
}

/**
 * A collection of values returned by getWorkerPools.
 */
export interface GetWorkerPoolsResult {
    readonly id: string;
    readonly workerPools: outputs.GetWorkerPoolsWorkerPool[];
}
export function getWorkerPoolsOutput(args?: GetWorkerPoolsOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetWorkerPoolsResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("spacelift:index/getWorkerPools:getWorkerPools", {
        "id": args.id,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getWorkerPools.
 */
export interface GetWorkerPoolsOutputArgs {
    id?: pulumi.Input<string>;
}
