// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class GitlabIntegration extends pulumi.CustomResource {
    /**
     * Get an existing GitlabIntegration resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: GitlabIntegrationState, opts?: pulumi.CustomResourceOptions): GitlabIntegration {
        return new GitlabIntegration(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'spacelift:index/gitlabIntegration:GitlabIntegration';

    /**
     * Returns true if the given object is an instance of GitlabIntegration.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is GitlabIntegration {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === GitlabIntegration.__pulumiType;
    }

    /**
     * API host URL
     */
    public readonly apiHost!: pulumi.Output<string>;
    /**
     * Description of the integration
     */
    public readonly description!: pulumi.Output<string | undefined>;
    /**
     * Is the GitLab integration the default for all spaces? If set to `true` the space must be set to `root` in `space_id` or
     * left empty which uses the default
     */
    public readonly isDefault!: pulumi.Output<boolean | undefined>;
    /**
     * Labels to set on the integration
     */
    public readonly labels!: pulumi.Output<string[] | undefined>;
    /**
     * The friendly name of the integration
     */
    public readonly name!: pulumi.Output<string>;
    /**
     * The GitLab API Token
     */
    public readonly privateToken!: pulumi.Output<string>;
    /**
     * ID (slug) of the space the integration is in; Default: `root`
     */
    public readonly spaceId!: pulumi.Output<string | undefined>;
    /**
     * User facing host URL.
     */
    public readonly userFacingHost!: pulumi.Output<string>;
    /**
     * VCS checks configured for GitLab repositories. Possible values: INDIVIDUAL, AGGREGATED, ALL. Defaults to INDIVIDUAL.
     */
    public readonly vcsChecks!: pulumi.Output<string | undefined>;
    /**
     * Secret for webhooks originating from GitLab repositories
     */
    public /*out*/ readonly webhookSecret!: pulumi.Output<string>;
    /**
     * URL for webhooks originating from GitLab repositories
     */
    public /*out*/ readonly webhookUrl!: pulumi.Output<string>;

    /**
     * Create a GitlabIntegration resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: GitlabIntegrationArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: GitlabIntegrationArgs | GitlabIntegrationState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as GitlabIntegrationState | undefined;
            resourceInputs["apiHost"] = state ? state.apiHost : undefined;
            resourceInputs["description"] = state ? state.description : undefined;
            resourceInputs["isDefault"] = state ? state.isDefault : undefined;
            resourceInputs["labels"] = state ? state.labels : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["privateToken"] = state ? state.privateToken : undefined;
            resourceInputs["spaceId"] = state ? state.spaceId : undefined;
            resourceInputs["userFacingHost"] = state ? state.userFacingHost : undefined;
            resourceInputs["vcsChecks"] = state ? state.vcsChecks : undefined;
            resourceInputs["webhookSecret"] = state ? state.webhookSecret : undefined;
            resourceInputs["webhookUrl"] = state ? state.webhookUrl : undefined;
        } else {
            const args = argsOrState as GitlabIntegrationArgs | undefined;
            if ((!args || args.apiHost === undefined) && !opts.urn) {
                throw new Error("Missing required property 'apiHost'");
            }
            if ((!args || args.privateToken === undefined) && !opts.urn) {
                throw new Error("Missing required property 'privateToken'");
            }
            if ((!args || args.userFacingHost === undefined) && !opts.urn) {
                throw new Error("Missing required property 'userFacingHost'");
            }
            resourceInputs["apiHost"] = args ? args.apiHost : undefined;
            resourceInputs["description"] = args ? args.description : undefined;
            resourceInputs["isDefault"] = args ? args.isDefault : undefined;
            resourceInputs["labels"] = args ? args.labels : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["privateToken"] = args?.privateToken ? pulumi.secret(args.privateToken) : undefined;
            resourceInputs["spaceId"] = args ? args.spaceId : undefined;
            resourceInputs["userFacingHost"] = args ? args.userFacingHost : undefined;
            resourceInputs["vcsChecks"] = args ? args.vcsChecks : undefined;
            resourceInputs["webhookSecret"] = undefined /*out*/;
            resourceInputs["webhookUrl"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["privateToken", "webhookSecret"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(GitlabIntegration.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering GitlabIntegration resources.
 */
export interface GitlabIntegrationState {
    /**
     * API host URL
     */
    apiHost?: pulumi.Input<string>;
    /**
     * Description of the integration
     */
    description?: pulumi.Input<string>;
    /**
     * Is the GitLab integration the default for all spaces? If set to `true` the space must be set to `root` in `space_id` or
     * left empty which uses the default
     */
    isDefault?: pulumi.Input<boolean>;
    /**
     * Labels to set on the integration
     */
    labels?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The friendly name of the integration
     */
    name?: pulumi.Input<string>;
    /**
     * The GitLab API Token
     */
    privateToken?: pulumi.Input<string>;
    /**
     * ID (slug) of the space the integration is in; Default: `root`
     */
    spaceId?: pulumi.Input<string>;
    /**
     * User facing host URL.
     */
    userFacingHost?: pulumi.Input<string>;
    /**
     * VCS checks configured for GitLab repositories. Possible values: INDIVIDUAL, AGGREGATED, ALL. Defaults to INDIVIDUAL.
     */
    vcsChecks?: pulumi.Input<string>;
    /**
     * Secret for webhooks originating from GitLab repositories
     */
    webhookSecret?: pulumi.Input<string>;
    /**
     * URL for webhooks originating from GitLab repositories
     */
    webhookUrl?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a GitlabIntegration resource.
 */
export interface GitlabIntegrationArgs {
    /**
     * API host URL
     */
    apiHost: pulumi.Input<string>;
    /**
     * Description of the integration
     */
    description?: pulumi.Input<string>;
    /**
     * Is the GitLab integration the default for all spaces? If set to `true` the space must be set to `root` in `space_id` or
     * left empty which uses the default
     */
    isDefault?: pulumi.Input<boolean>;
    /**
     * Labels to set on the integration
     */
    labels?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The friendly name of the integration
     */
    name?: pulumi.Input<string>;
    /**
     * The GitLab API Token
     */
    privateToken: pulumi.Input<string>;
    /**
     * ID (slug) of the space the integration is in; Default: `root`
     */
    spaceId?: pulumi.Input<string>;
    /**
     * User facing host URL.
     */
    userFacingHost: pulumi.Input<string>;
    /**
     * VCS checks configured for GitLab repositories. Possible values: INDIVIDUAL, AGGREGATED, ALL. Defaults to INDIVIDUAL.
     */
    vcsChecks?: pulumi.Input<string>;
}
