// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class MountedFile extends pulumi.CustomResource {
    /**
     * Get an existing MountedFile resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: MountedFileState, opts?: pulumi.CustomResourceOptions): MountedFile {
        return new MountedFile(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'spacelift:index/mountedFile:MountedFile';

    /**
     * Returns true if the given object is an instance of MountedFile.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is MountedFile {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === MountedFile.__pulumiType;
    }

    /**
     * SHA-256 checksum of the value
     */
    public /*out*/ readonly checksum!: pulumi.Output<string>;
    /**
     * Content of the mounted file encoded using Base-64
     */
    public readonly content!: pulumi.Output<string>;
    /**
     * ID of the context on which the mounted file is defined
     */
    public readonly contextId!: pulumi.Output<string | undefined>;
    /**
     * Free-form description of the mounted file
     */
    public readonly description!: pulumi.Output<string | undefined>;
    /**
     * ID of the module on which the mounted file is defined
     */
    public readonly moduleId!: pulumi.Output<string | undefined>;
    public readonly mountedFileId!: pulumi.Output<string>;
    /**
     * Relative path to the mounted file, without the /mnt/workspace/ prefix
     */
    public readonly relativePath!: pulumi.Output<string>;
    /**
     * ID of the stack on which the mounted file is defined
     */
    public readonly stackId!: pulumi.Output<string | undefined>;
    /**
     * Indicates whether the content can be read back outside a Run. Defaults to `true`.
     */
    public readonly writeOnly!: pulumi.Output<boolean | undefined>;

    /**
     * Create a MountedFile resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: MountedFileArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: MountedFileArgs | MountedFileState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as MountedFileState | undefined;
            resourceInputs["checksum"] = state ? state.checksum : undefined;
            resourceInputs["content"] = state ? state.content : undefined;
            resourceInputs["contextId"] = state ? state.contextId : undefined;
            resourceInputs["description"] = state ? state.description : undefined;
            resourceInputs["moduleId"] = state ? state.moduleId : undefined;
            resourceInputs["mountedFileId"] = state ? state.mountedFileId : undefined;
            resourceInputs["relativePath"] = state ? state.relativePath : undefined;
            resourceInputs["stackId"] = state ? state.stackId : undefined;
            resourceInputs["writeOnly"] = state ? state.writeOnly : undefined;
        } else {
            const args = argsOrState as MountedFileArgs | undefined;
            if ((!args || args.content === undefined) && !opts.urn) {
                throw new Error("Missing required property 'content'");
            }
            if ((!args || args.relativePath === undefined) && !opts.urn) {
                throw new Error("Missing required property 'relativePath'");
            }
            resourceInputs["content"] = args?.content ? pulumi.secret(args.content) : undefined;
            resourceInputs["contextId"] = args ? args.contextId : undefined;
            resourceInputs["description"] = args ? args.description : undefined;
            resourceInputs["moduleId"] = args ? args.moduleId : undefined;
            resourceInputs["mountedFileId"] = args ? args.mountedFileId : undefined;
            resourceInputs["relativePath"] = args ? args.relativePath : undefined;
            resourceInputs["stackId"] = args ? args.stackId : undefined;
            resourceInputs["writeOnly"] = args ? args.writeOnly : undefined;
            resourceInputs["checksum"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["content"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(MountedFile.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering MountedFile resources.
 */
export interface MountedFileState {
    /**
     * SHA-256 checksum of the value
     */
    checksum?: pulumi.Input<string>;
    /**
     * Content of the mounted file encoded using Base-64
     */
    content?: pulumi.Input<string>;
    /**
     * ID of the context on which the mounted file is defined
     */
    contextId?: pulumi.Input<string>;
    /**
     * Free-form description of the mounted file
     */
    description?: pulumi.Input<string>;
    /**
     * ID of the module on which the mounted file is defined
     */
    moduleId?: pulumi.Input<string>;
    mountedFileId?: pulumi.Input<string>;
    /**
     * Relative path to the mounted file, without the /mnt/workspace/ prefix
     */
    relativePath?: pulumi.Input<string>;
    /**
     * ID of the stack on which the mounted file is defined
     */
    stackId?: pulumi.Input<string>;
    /**
     * Indicates whether the content can be read back outside a Run. Defaults to `true`.
     */
    writeOnly?: pulumi.Input<boolean>;
}

/**
 * The set of arguments for constructing a MountedFile resource.
 */
export interface MountedFileArgs {
    /**
     * Content of the mounted file encoded using Base-64
     */
    content: pulumi.Input<string>;
    /**
     * ID of the context on which the mounted file is defined
     */
    contextId?: pulumi.Input<string>;
    /**
     * Free-form description of the mounted file
     */
    description?: pulumi.Input<string>;
    /**
     * ID of the module on which the mounted file is defined
     */
    moduleId?: pulumi.Input<string>;
    mountedFileId?: pulumi.Input<string>;
    /**
     * Relative path to the mounted file, without the /mnt/workspace/ prefix
     */
    relativePath: pulumi.Input<string>;
    /**
     * ID of the stack on which the mounted file is defined
     */
    stackId?: pulumi.Input<string>;
    /**
     * Indicates whether the content can be read back outside a Run. Defaults to `true`.
     */
    writeOnly?: pulumi.Input<boolean>;
}
