// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class PolicyAttachment extends pulumi.CustomResource {
    /**
     * Get an existing PolicyAttachment resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: PolicyAttachmentState, opts?: pulumi.CustomResourceOptions): PolicyAttachment {
        return new PolicyAttachment(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'spacelift:index/policyAttachment:PolicyAttachment';

    /**
     * Returns true if the given object is an instance of PolicyAttachment.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is PolicyAttachment {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === PolicyAttachment.__pulumiType;
    }

    /**
     * ID of the module to attach the policy to
     */
    public readonly moduleId!: pulumi.Output<string | undefined>;
    public readonly policyAttachmentId!: pulumi.Output<string>;
    /**
     * ID of the policy to attach
     */
    public readonly policyId!: pulumi.Output<string>;
    /**
     * ID of the stack to attach the policy to
     */
    public readonly stackId!: pulumi.Output<string | undefined>;

    /**
     * Create a PolicyAttachment resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: PolicyAttachmentArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: PolicyAttachmentArgs | PolicyAttachmentState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as PolicyAttachmentState | undefined;
            resourceInputs["moduleId"] = state ? state.moduleId : undefined;
            resourceInputs["policyAttachmentId"] = state ? state.policyAttachmentId : undefined;
            resourceInputs["policyId"] = state ? state.policyId : undefined;
            resourceInputs["stackId"] = state ? state.stackId : undefined;
        } else {
            const args = argsOrState as PolicyAttachmentArgs | undefined;
            if ((!args || args.policyId === undefined) && !opts.urn) {
                throw new Error("Missing required property 'policyId'");
            }
            resourceInputs["moduleId"] = args ? args.moduleId : undefined;
            resourceInputs["policyAttachmentId"] = args ? args.policyAttachmentId : undefined;
            resourceInputs["policyId"] = args ? args.policyId : undefined;
            resourceInputs["stackId"] = args ? args.stackId : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(PolicyAttachment.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering PolicyAttachment resources.
 */
export interface PolicyAttachmentState {
    /**
     * ID of the module to attach the policy to
     */
    moduleId?: pulumi.Input<string>;
    policyAttachmentId?: pulumi.Input<string>;
    /**
     * ID of the policy to attach
     */
    policyId?: pulumi.Input<string>;
    /**
     * ID of the stack to attach the policy to
     */
    stackId?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a PolicyAttachment resource.
 */
export interface PolicyAttachmentArgs {
    /**
     * ID of the module to attach the policy to
     */
    moduleId?: pulumi.Input<string>;
    policyAttachmentId?: pulumi.Input<string>;
    /**
     * ID of the policy to attach
     */
    policyId: pulumi.Input<string>;
    /**
     * ID of the stack to attach the policy to
     */
    stackId?: pulumi.Input<string>;
}
