// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class Role extends pulumi.CustomResource {
    /**
     * Get an existing Role resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: RoleState, opts?: pulumi.CustomResourceOptions): Role {
        return new Role(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'spacelift-terraform-provider:index/role:Role';

    /**
     * Returns true if the given object is an instance of Role.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Role {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Role.__pulumiType;
    }

    /**
     * List of actions (permissions) associated with the role. For example: `SPACE_READ`, `SPACE_WRITE`, `SPACE_ADMIN`,
     * `RUN_TRIGGER`. All possible actions can be listed using the `spacelift-terraform-provider.getRoleActions` data source.
     */
    declare public readonly actions: pulumi.Output<string[]>;
    /**
     * Human-readable, free-form description of the role
     */
    declare public readonly description: pulumi.Output<string | undefined>;
    /**
     * Human-readable, free-form name of the role
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * URL-friendly unique identifier of the role, generated from the name. Example: `space-admin`.
     */
    declare public /*out*/ readonly slug: pulumi.Output<string>;

    /**
     * Create a Role resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: RoleArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: RoleArgs | RoleState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as RoleState | undefined;
            resourceInputs["actions"] = state?.actions;
            resourceInputs["description"] = state?.description;
            resourceInputs["name"] = state?.name;
            resourceInputs["slug"] = state?.slug;
        } else {
            const args = argsOrState as RoleArgs | undefined;
            if (args?.actions === undefined && !opts.urn) {
                throw new Error("Missing required property 'actions'");
            }
            resourceInputs["actions"] = args?.actions;
            resourceInputs["description"] = args?.description;
            resourceInputs["name"] = args?.name;
            resourceInputs["slug"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Role.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering Role resources.
 */
export interface RoleState {
    /**
     * List of actions (permissions) associated with the role. For example: `SPACE_READ`, `SPACE_WRITE`, `SPACE_ADMIN`,
     * `RUN_TRIGGER`. All possible actions can be listed using the `spacelift-terraform-provider.getRoleActions` data source.
     */
    actions?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Human-readable, free-form description of the role
     */
    description?: pulumi.Input<string>;
    /**
     * Human-readable, free-form name of the role
     */
    name?: pulumi.Input<string>;
    /**
     * URL-friendly unique identifier of the role, generated from the name. Example: `space-admin`.
     */
    slug?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a Role resource.
 */
export interface RoleArgs {
    /**
     * List of actions (permissions) associated with the role. For example: `SPACE_READ`, `SPACE_WRITE`, `SPACE_ADMIN`,
     * `RUN_TRIGGER`. All possible actions can be listed using the `spacelift-terraform-provider.getRoleActions` data source.
     */
    actions: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Human-readable, free-form description of the role
     */
    description?: pulumi.Input<string>;
    /**
     * Human-readable, free-form name of the role
     */
    name?: pulumi.Input<string>;
}
