// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class Task extends pulumi.CustomResource {
    /**
     * Get an existing Task resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: TaskState, opts?: pulumi.CustomResourceOptions): Task {
        return new Task(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'spacelift:index/task:Task';

    /**
     * Returns true if the given object is an instance of Task.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Task {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Task.__pulumiType;
    }

    /**
     * Command that will be run.
     */
    public readonly command!: pulumi.Output<string>;
    /**
     * Whether to initialize the stack or not. Default: `true`
     */
    public readonly init!: pulumi.Output<boolean | undefined>;
    /**
     * Arbitrary map of values that, when changed, will trigger recreation of the resource.
     */
    public readonly keepers!: pulumi.Output<{[key: string]: string} | undefined>;
    /**
     * ID of the stack for which to run the task
     */
    public readonly stackId!: pulumi.Output<string>;
    public readonly taskId!: pulumi.Output<string>;
    public readonly timeouts!: pulumi.Output<outputs.TaskTimeouts | undefined>;
    /**
     * Wait for the run to finish
     */
    public readonly wait!: pulumi.Output<outputs.TaskWait | undefined>;

    /**
     * Create a Task resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: TaskArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: TaskArgs | TaskState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as TaskState | undefined;
            resourceInputs["command"] = state ? state.command : undefined;
            resourceInputs["init"] = state ? state.init : undefined;
            resourceInputs["keepers"] = state ? state.keepers : undefined;
            resourceInputs["stackId"] = state ? state.stackId : undefined;
            resourceInputs["taskId"] = state ? state.taskId : undefined;
            resourceInputs["timeouts"] = state ? state.timeouts : undefined;
            resourceInputs["wait"] = state ? state.wait : undefined;
        } else {
            const args = argsOrState as TaskArgs | undefined;
            if ((!args || args.command === undefined) && !opts.urn) {
                throw new Error("Missing required property 'command'");
            }
            if ((!args || args.stackId === undefined) && !opts.urn) {
                throw new Error("Missing required property 'stackId'");
            }
            resourceInputs["command"] = args ? args.command : undefined;
            resourceInputs["init"] = args ? args.init : undefined;
            resourceInputs["keepers"] = args ? args.keepers : undefined;
            resourceInputs["stackId"] = args ? args.stackId : undefined;
            resourceInputs["taskId"] = args ? args.taskId : undefined;
            resourceInputs["timeouts"] = args ? args.timeouts : undefined;
            resourceInputs["wait"] = args ? args.wait : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Task.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering Task resources.
 */
export interface TaskState {
    /**
     * Command that will be run.
     */
    command?: pulumi.Input<string>;
    /**
     * Whether to initialize the stack or not. Default: `true`
     */
    init?: pulumi.Input<boolean>;
    /**
     * Arbitrary map of values that, when changed, will trigger recreation of the resource.
     */
    keepers?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    /**
     * ID of the stack for which to run the task
     */
    stackId?: pulumi.Input<string>;
    taskId?: pulumi.Input<string>;
    timeouts?: pulumi.Input<inputs.TaskTimeouts>;
    /**
     * Wait for the run to finish
     */
    wait?: pulumi.Input<inputs.TaskWait>;
}

/**
 * The set of arguments for constructing a Task resource.
 */
export interface TaskArgs {
    /**
     * Command that will be run.
     */
    command: pulumi.Input<string>;
    /**
     * Whether to initialize the stack or not. Default: `true`
     */
    init?: pulumi.Input<boolean>;
    /**
     * Arbitrary map of values that, when changed, will trigger recreation of the resource.
     */
    keepers?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    /**
     * ID of the stack for which to run the task
     */
    stackId: pulumi.Input<string>;
    taskId?: pulumi.Input<string>;
    timeouts?: pulumi.Input<inputs.TaskTimeouts>;
    /**
     * Wait for the run to finish
     */
    wait?: pulumi.Input<inputs.TaskWait>;
}
